### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by Anakin2012** [MATF-RG17/RG108-labyrinth#1]
Projekat zavrsen.

**Comment by ivan-cukic-matf** [comment]
Otvorite ovo ponovo kad budete uradili #2

Rok za završetak je 10. septembar.

**Comment by Anakin2012** [comment]
@ivan-cukic-matf 
Promenila sam da se gluNewQuadric poziva samo jednom u main-u, sada ne bi trebalo da postoji curenje.
